version: '3'

services:

  rabbit:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: digitaleq
      RABBITMQ_DEFAULT_PASS: digitaleq
    restart: always
    networks:
      - eq-runner
    ports:
      - "5672:5672"
      - "15672:15672"

  eq-survey-runner-db:
    image: postgres:9.4
    environment:
      POSTGRES_PASSWORD: digitaleq
      POSTGRES_USER: digitaleq
      POSTGRES_DB: runner
    restart: always
    networks:
      - eq-runner
    ports:
      - 5432

  eq-survey-register:
    image: onsdigital/eq-survey-register
    restart: always
    networks:
      - eq-runner
    ports:
      - "8080:8080"

  eq-survey-runner:
    image: onsdigital/eq-survey-runner
    environment:
      EQ_DEV_MODE: "True"
      EQ_DEVELOPER_LOGGING: "True"
      EQ_SERVER_SIDE_STORAGE_DATABASE_HOST: eq-survey-runner-db
      EQ_SERVER_SIDE_STORAGE_DATABASE_NAME: runner
      EQ_ENABLE_SECURE_SESSION_COOKIE: "False"
      EQ_RABBITMQ_HOST: rabbit
      EQ_RABBITMQ_HOST_SECONDARY: rabbit
      EQ_SECRETS_FILE: docker-secrets.yml
      EQ_KEYS_FILE: docker-keys.yml
      EQ_DYNAMODB_ENDPOINT: http://eq-survey-runner-dynamodb:8000
      EQ_SUBMITTED_RESPONSES_TABLE_NAME: dev-submitted-responses
      EQ_QUESTIONNAIRE_STATE_TABLE_NAME: dev-questionnaire-state
      EQ_QUESTIONNAIRE_STATE_DYNAMO_READ: "True"
      EQ_QUESTIONNAIRE_STATE_DYNAMO_WRITE: "True"
      EQ_SESSION_TABLE_NAME: dev-eq-session
      EQ_SESSION_DYNAMO_READ: "True"
      EQ_SESSION_DYNAMO_WRITE: "True"
      EQ_USED_JTI_CLAIM_TABLE_NAME: dev-used-jti-claim
      EQ_USED_JTI_CLAIM_DYNAMO_READ: "True"
      EQ_USED_JTI_CLAIM_DYNAM_WRITE: "True"
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
    depends_on:
      - eq-survey-runner-db
      - rabbit
      - eq-survey-runner-dynamodb
    restart: always
    networks:
      - eq-runner
    ports:
      - "5000:5000"

  eq-survey-launcher:
    image: onsdigital/go-launch-a-survey
    environment:
      SURVEY_RUNNER_URL: http://localhost:5000
      SURVEY_RUNNER_SCHEMA_URL: http://eq-survey-runner:5000
      SURVEY_REGISTER_URL: http://eq-survey-register:8080
      SCHEMA_VALIDATOR_URL: http://eq-schema-validator:5000
    depends_on:
      - eq-survey-runner
      - eq-survey-register
      - eq-schema-validator
    restart: always
    networks:
      - eq-runner
    ports:
      - "8000:8000"

  eq-survey-runner-dynamodb:
    image: onsdigital/eq-docker-dynamodb:latest
    restart: always
    networks:
      - eq-runner
    ports:
      - "6060:8000"

  eq-schema-validator:
    image: onsdigital/eq-schema-validator
    ports:
      - "5001:5000"
    networks:
      - eq-runner
      - eq-author
    restart: always

  eq-author:
    image: onsdigital/eq-author
    environment:
      REACT_APP_BASE_NAME: /eq-author
      REACT_APP_API_URL: http://localhost:4000/graphql
      REACT_APP_USE_MOCK_API: "false"
      REACT_APP_LAUNCH_URL: http://localhost:4000/launch
      REACT_APP_ENABLE_AUTH: "${AUTHOR_ENABLE_AUTH:-false}"
      REACT_APP_FIREBASE_PROJECT_ID: "${AUTHOR_FIREBASE_PROJECT_ID:-FAKE_ID}"
      REACT_APP_FIREBASE_API_KEY: "${AUTHOR_FIREBASE_API_KEY:-FAKE_API_KEY}"
      REACT_APP_FIREBASE_MESSAGING_SENDER_ID: "${AUTHOR_FIREBASE_MESSAGING_SENDER_ID:-FAKE_SENDER_ID}"
    depends_on:
      - eq-author-api
    restart: always
    networks:
      - eq-author
    ports:
      - 3000:3000

  eq-author-api:
    image: onsdigital/eq-author-api
    environment:
      DB_CONNECTION_URI: postgres://postgres:mysecretpassword@eq-author-db:5432/postgres
      RUNNER_SESSION_URL: http://localhost:5000/session?token=
      PUBLISHER_URL: http://eq-publisher:9000/publish/
    depends_on:
      - eq-author-db
    restart: always
    networks:
      - eq-author
    ports:
      - 4000:4000

  eq-publisher:
    image: onsdigital/eq-publisher
    environment:
      EQ_AUTHOR_API_URL: http://eq-author-api:4000/graphql
      EQ_SCHEMA_VALIDATOR_URL: http://eq-schema-validator:5000/validate
    depends_on:
      - eq-author-api
      - eq-schema-validator
    restart: always
    networks:
      - eq-author
      - eq-runner
    ports:
      - 9000:9000

  eq-author-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    restart: always
    networks:
      - eq-author
    ports:
      - 5432

networks:
  eq-runner:
    driver: bridge
  eq-author:
    driver: bridge
